//------------------COMMENT ------
export const CREATE_COMMENT_SAGA = "CREATE_COMMENT_SAGA";
export const CREATE_COMMENT_MODAL = "CREATE_COMMENT_MODAL";
export const GET_COMMENT_ALL_SAGA = "GET_COMMENT_ALL_SAGA";
export const GET_COMMENT_ALL = "GET_COMMENT_ALL";
export const UPDATE_COMMENT_SAGA = "UPDATE_COMMENT_SAGA";
export const DELETE_COMMENT_SAGA = "DELETE_COMMENT_SAGA";
