//------------------PROJECT ------
export const GET_LIST_PROJECT = "GET_LIST_PROJECT";
export const GET_LIST_PROJECT_SAGA = "GET_LIST_PROJECT_SAGA";
export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";
export const OPEN_FORM_EDIT_PROJECT = "OPEN_FORM_EDIT_PROJECT";
export const SET_SUBMIT_EDIT_PROJECT = "SET_SUBMIT_EDIT_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const UPDATE_PROJECT_SAGA = "UPDATE_PROJECT_SAGA";
export const DELETE_PROJECT_SAGA = "DELETE_PROJECT_SAGA";
export const GET_PROJECT_DETAIL = "GET_PROJECT_DETAIL";
export const PUT_PROJECT_DETAIL = "PUT_PROJECT_DETAIL";
export const OPEN_FORM_CREATE_TASK = "OPEN_FORM_CREATE_TASK";
export const GET_ALL_PROJECT = "GET_ALL_PROJECT";
export const GET_ALL_PROJECT_SAGA = "GET_ALL_PROJECT_SAGA";
