export const USER_SIGNIN_API = "USER_SIGNIN_API";
export const GET_USER_API = "GET_USER_API";
export const GET_USER_SEARCH = "GET_USER_SEARCH";
export const ADD_USER_PROJECT_API = "ADD_USER_PROJECT_API";
export const REMOVE_USER_PROJECT_API = "REMOVE_USER_PROJECT_API";

export const GET_USER_BY_PROJECT_ID_SAGA = "GET_USER_BY_PROJECT_ID_SAGA";
export const GET_USER_BY_PROJECT_ID = "GET_USER_BY_PROJECT_ID";

export const SIGNUP_SAGA = "SIGNUP_SAGA";
export const UPDATE_USER_SAGA = "UPDATE_USER_SAGA";
export const DELETE_USER_SAGA = "DELETE_USER_SAGA";

export const OPEN_FORM_CREATE_USER = "OPEN_FORM_CREATE_USER";
export const SET_SUBMIT_CREATE_USER = "SET_SUBMIT_CREATE_USER";

export const OPEN_FORM_EDIT_USER = "OPEN_FORM_EDIT_USER";
export const SET_SUBMIT_EDIT_USER = "SET_SUBMIT_EDIT_USER";

export const EDIT_USER = "EDIT_USER";
